### ISSUE TITLE
Not able to detect beacons

### ISSUE THREAD

**Issue by TeliAkshay** [kontaktio/kontakt-beacon-admin-sample-app#26]
I am using the sample code provided on Github but I am not able to detect any beacons, Tried various ways but not able to detect any. I am working on stimulated Beacons using "https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=en_IN". I am trying to do POC to fetch distance between beacon and scanner.

**Comment by robertbielas** [comment]
@TeliAkshay This issue is old now, but if you are still interested: you may try to use nrfConnect app to see if your phone detects your desired beacons. It may be a phone specific-issue, and diagnosing the problem using another app unrelated to the sdk may get you closer to the solution.

I am going to close it now, but feel free to reopen if you still have any troubles. Thanks!
