### ISSUE TITLE
Background Scan Issue

### ISSUE THREAD

**Issue by ankitnarang07** [kontaktio/kontakt-beacon-admin-sample-app#8]
We are using https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app-module/src/main/java/com/kontakt/sample/service/BackgroundScanService.java Service for beacon detection in background but it is not scanning all the time. It stops scanning itself after some time intervals. 

What we need to do is to generate Notification on detection of beacon when app is in background.

Below is the code snippet where we are placing notification code:

private final ScanContext scanContext = new ScanContext.Builder() 
.setScanMode(ProximityManager.SCAN_MODE_BALANCED) 
.setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT) 
.setForceScanConfiguration(ForceScanConfiguration.DEFAULT) 
.setIBeaconScanContext(new IBeaconScanContext.Builder() 
.setEventTypes(EnumSet.of( 
EventType.SPACE_ENTERED, 
EventType.DEVICE_DISCOVERED, 
EventType.SPACE_ABANDONED 
)) 
.setIBeaconFilters(Collections.singleton(new IBeaconFilter() { 
@Override 
public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) { 
final UUID proximityUUID = iBeaconAdvertisingPacket.getProximityUUID(); 
final double distance = iBeaconAdvertisingPacket.getDistance();

//************************************************************************// 
//This function is to show Notification on Bar. 
generateNotification();

return proximityUUID.equals(KontaktSDK.DEFAULT_KONTAKT_BEACON_PROXIMITY_UUID) && distance <= ACCEPT_DISTANCE; 
} 
})) 
.build()) 
.build();

Please guide us for any code changes or if there is some issue with SDK code, that it stops scanning after some interval.

**Comment by jakubkontakt** [comment]
Have you checked that your service is not killed by Android OS?

**Comment by ankitnarang07** [comment]
We have no idea about OS but In our code we are not stopping service anywhere and It shows toast with message Region Abandoned when it stops scanning.

**Comment by kapilok2014** [comment]
Continuous scanning is bad for battery life. Could it be that the scanner scans for x seconds, then waits for y seconds ... and so on?
-Kapil

**Comment by jakubkontakt** [comment]
@ankitnarang07 
I can't help you without more details about your error. Do you have any stacktrace or logs from your service? Please note that this service is returning START_NOT_STICKY flag. 

This means that if your service is killed by Android it will not be recreated. Read this stackoverflow thread about background services http://stackoverflow.com/questions/12219249/background-service-getting-killed-in-android. 

@kapilok2014 
You do not have to make scan continuous, providing <b>ScanPeriod</b> to ScanContext will affect in different behaviour of your scan. By default ScanPeriod is Ranging, which is meant to be continuous.

**Comment by Mukesh-Singh** [comment]
We are using this service 
https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app-module/src/main/java/com/kontakt/sample/service/BackgroundScanService.java
for scan/monitor the kontakt - beacon devices in background but whenever app is killed it stop the scanning and does not send any notification.

How can scan the beacons in background means when app is killed or not running ?

**Comment by SaikCaskey** [comment]
You could have a START_STICKY background service and a task that periodically ensures that it is still running, or starts it otherwise. You absolutely shouldn't though, not unless your user wants this or you have some requirement and the user is made well aware. 

Mobile is now so involved and intimate, the mentality should always be 'create user value with excellent software' not 'snatch as much as we can from that idiot actually using our software'. It is because of dirty snatchers and gullible users that I now have to deal with people like Huawei and Samsung interfering to "optimise" battery, GPS and BLE.

**Comment by robertbielas** [comment]
Old issue, but still relevant. 

@kapilok2014 Your intuition is correct! Yes, OS can silently kill BT scanner if it runs continuously for a very long time (especially since Android 7; then we have other restrictions like the inability to run more than 5 startScan() operations in less than 7 minutes and whatnots; as you may guess, this is not developer friendly solution).

@ankitnarang07 
In order to manipulate this, you can add e.g. this line to your scan config:
 
 new ScanContext.Builder().scanPeriod(ScanPeriod.create(TimeUnit.MINUTES.toMillis(10), 500)); //and other settings you are interested in
 
^ this tells the sdk that it should scan for 10 minutes, and then take a break for 500 milliseconds. Because the rule is that the singular BT scan should not take any longer than 30 minutes on Android 7, this trick should do. 

Also, because the issue has "Background scan" in its title, you can be interested in the possibilities offered by the sdk 5.0.7 for newer Android phones - please see the changelog (https://knowledgebase.kontakt.io/mobile/android/changelog/)  and our sample application.

Because the issue is old now, I am going to close this, but feel free to reopen if you still have any troubles! Thanks!
